#pragma config(Hubs,  S1, HTMotor,  HTServo,  HTMotor,  none)
#pragma config(Hubs,  S2, HTMotor,  HTServo,  HTMotor,  none)
#pragma config(Sensor, S1,     ,               sensorI2CMuxController)
#pragma config(Sensor, S2,     ,               sensorI2CMuxController)
#pragma config(Motor,  motorA,           ,             tmotorNXT, openLoop)
#pragma config(Motor,  motorB,           ,             tmotorNXT, openLoop)
#pragma config(Motor,  motorC,           ,             tmotorNXT, openLoop)
#pragma config(Motor,  mtr_S1_C1_1,     motorD,        tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C1_2,     motorE,        tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C3_1,     motorF,        tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C3_2,     motorG,        tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S2_C1_1,     motorH,        tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S2_C1_2,     motorI,        tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S2_C3_1,     motorJ,        tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S2_C3_2,     motorK,        tmotorTetrix, openLoop)
#pragma config(Servo,  srvo_S1_C2_1,    servo1,               tServoNone)
#pragma config(Servo,  srvo_S1_C2_2,    servo2,               tServoNone)
#pragma config(Servo,  srvo_S1_C2_3,    servo3,               tServoNone)
#pragma config(Servo,  srvo_S1_C2_4,    servo4,               tServoNone)
#pragma config(Servo,  srvo_S1_C2_5,    servo5,               tServoNone)
#pragma config(Servo,  srvo_S1_C2_6,    servo6,               tServoNone)
#pragma config(Servo,  srvo_S2_C2_1,    servo7,               tServoNone)
#pragma config(Servo,  srvo_S2_C2_2,    servo8,               tServoNone)
#pragma config(Servo,  srvo_S2_C2_3,    servo9,               tServoNone)
#pragma config(Servo,  srvo_S2_C2_4,    servo10,              tServoNone)
#pragma config(Servo,  srvo_S2_C2_5,    servo11,              tServoNone)
#pragma config(Servo,  srvo_S2_C2_6,    servo12,              tServoNone)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

///version 1.1 changed 21.08.2014 by GEORGE KRYLOV

#define Forward_L motorH
#define Forward_R motorE
#define Backward_L motorI
#define Backward_R motorD
#define S_Forward_L servo4
#define S_Backward_L servo11
#define S_Backward_R servo5
#define S_Forward_R servo6
#define S_Flag_Raise1 servo1
#define S_Flag_Raise2 servo2
#define S_Flag_Raise3 servo3
#define S_Autonom_Cube servo12

#define Capture_Control_Raise_1 motor[motorA]
#define Capture_Control_Raise_2 motor[motorB]
#define Capture_Raise_1 motor[motorF]
#define Capture_Raise_2 motor[motorG]
#define Robot_Raise_1 motor[motorJ]
#define Robot_Raise_2 motor[motorK]
#define Capture_Control servo[servo10]

const signed char speed_Forward_L = 100;
const signed char m_speed_Forward_L = -100;
const signed char speed_Forward_R = 100;
const signed char m_speed_Forward_R = -100;
const signed char speed_Backward_L = 100;
const signed char m_speed_Backward_L = -100;
const signed char speed_Backward_R = 100;
const signed char m_speed_Backward_R = -100;

const signed char slow_speed_Forward_L = 20;
const signed char slow_m_speed_Forward_L = -20;
const signed char slow_speed_Forward_R = 20;
const signed char slow_m_speed_Forward_R = -20;
const signed char slow_speed_Backward_L = 20;
const signed char slow_m_speed_Backward_L = -20;
const signed char slow_speed_Backward_R = 20;
const signed char slow_m_speed_Backward_R = -20;

#include "JoystickDriver.c"

void initializeRobot()
{
  return;
}

task flag_raise_and_autonom_cube()
{
	bool flag_Autonom_Cube = false;

	while (true)
	{
		while (joy1Btn (9))
		{
			servo[S_Flag_Raise1] = 256; /* 0 - Full Power/ Speed Reverse; 127 - Stop; 256 - Full Power/ Speed Forward */
			servo[S_Flag_Raise2] = 256;
			servo[S_Flag_Raise3] = 0;
		}

		servo[S_Flag_Raise1] = 127;
	  servo[S_Flag_Raise2] = 127;
	  servo[S_Flag_Raise3] = 127;

	  if (joy1Btn (10))
    {
    	flag_Autonom_Cube = !flag_Autonom_Cube;

      if (flag_Autonom_Cube)
      	servo[S_Autonom_Cube] = 255;
 	    else
 	    	servo[S_Autonom_Cube] = 0;

    	while (joy1Btn (10))
    		getJoystickSettings(joystick);
    }
	}
}

task move()
{
	const signed char stic_pog = 10, m_stic_pog = -10;
	const float small_k = 0.3, m_small_k = -0.3, big_k = 0.45, m_big_k = -0.45;
	int i = 0;

	while (true)
	{
		if (joy1Btn (4))
	  {
	  	servo[S_Forward_L] = 255;
			servo[S_Forward_R] = 0;
			servo[S_Backward_L] = 0;
			servo[S_Backward_R] = 255;

			if (i != 0)
			{
				wait10Msec(50);
				i = 0;
			}

			while (joy1Btn (4)) /* move forward*/
			{
				motor[Forward_L] = m_speed_Forward_L;
				motor[Forward_R] = speed_Forward_R;
				motor[Backward_L] = m_speed_Backward_L;
				motor[Backward_R] = speed_Backward_R;
			}

			motor[Forward_L] = 0;
			motor[Forward_R] = 0;
			motor[Backward_L] = 0;
			motor[Backward_R] = 0;
		}

		if (joy1Btn (2))
	  {
	  	servo[S_Forward_L] = 255;
			servo[S_Forward_R] = 0;
			servo[S_Backward_L] = 0;
			servo[S_Backward_R] = 255;

			if (i != 0)
			{
				wait10Msec(50);
				i = 0;
			}

			while (joy1Btn (2)) /* move backward */
			{
				motor[Forward_L] = speed_Forward_L;
				motor[Forward_R] = m_speed_Forward_R;
				motor[Backward_L] = speed_Backward_L;
				motor[Backward_R] = m_speed_Backward_R;
			}

			motor[Forward_L] = 0;
			motor[Forward_R] = 0;
			motor[Backward_L] = 0;
			motor[Backward_R] = 0;
		}

		if (joy1Btn (1))
	  {
	  	servo[S_Forward_L] = 0;
			servo[S_Forward_R] = 255;
			servo[S_Backward_L] = 255;
			servo[S_Backward_R] = 0;

			if (i != 1)
			{
				wait10Msec(50);
				i = 1;
			}

			while (joy1Btn (1)) /* move left */
			{
				motor[Forward_L] = speed_Forward_L;
				motor[Forward_R] = m_speed_Forward_R;
				motor[Backward_L] = m_speed_Backward_L;
				motor[Backward_R] = speed_Backward_R;
			}

			motor[Forward_L] = 0;
			motor[Forward_R] = 0;
			motor[Backward_L] = 0;
			motor[Backward_R] = 0;
		}

		if (joy1Btn (3))
	  {
	  	servo[S_Forward_L] = 0;
			servo[S_Forward_R] = 255;
			servo[S_Backward_L] = 255;
			servo[S_Backward_R] = 0;

			if (i != 1)
			{
				wait10Msec(50);
				i = 1;
			}

	  	while (joy1Btn (3)) /* move right */
	  	{
	  		motor[Forward_L] = m_speed_Forward_L;
				motor[Forward_R] = speed_Forward_R;
				motor[Backward_L] = speed_Backward_L;
				motor[Backward_R] = m_speed_Backward_R;
	  	}

	  	motor[Forward_L] = 0;
			motor[Forward_R] = 0;
			motor[Backward_L] = 0;
			motor[Backward_R] = 0;
	  }

	  if (joy1Btn (8))
		{
			servo[S_Forward_L] = 128;
			servo[S_Forward_R] = 128;
			servo[S_Backward_L] = 128;
			servo[S_Backward_R] = 128;

			if (i != 2)
			{
				wait10Msec(50);
				i = 2;
			}

			while (joy1Btn (8)) /* turn right*/
			{
				motor[Forward_L] = m_speed_Forward_L;
				motor[Forward_R] = m_speed_Forward_R;
				motor[Backward_L] = m_speed_Backward_L;
				motor[Backward_R] = m_speed_Backward_R;
			}

			motor[Forward_L] = 0;
			motor[Forward_R] = 0;
			motor[Backward_L] = 0;
			motor[Backward_R] = 0;
		}

		if (joy1Btn (7))
		{
			servo[S_Forward_L] = 128;
			servo[S_Forward_R] = 128;
			servo[S_Backward_L] = 128;
			servo[S_Backward_R] = 128;

			if (i != 2)
			{
				wait10Msec(50);
				i = 2;
			}

			while (joy1Btn (7)) /* turn left */
			{
				motor[Forward_L] = speed_Forward_L;
				motor[Forward_R] = speed_Forward_R;
				motor[Backward_L] = speed_Backward_L;
				motor[Backward_R] = speed_Backward_R;
			}

			motor[Forward_L] = 0;
			motor[Forward_R] = 0;
			motor[Backward_L] = 0;
			motor[Backward_R] = 0;
		}

		if (joy1Btn (5))
	  {
	  	servo[S_Forward_L] = 128;
			servo[S_Forward_R] = 128;
			servo[S_Backward_L] = 128;
			servo[S_Backward_R] = 128;

			if (i != 2)
			{
				wait10Msec(50);
				i = 2;
			}

			while (joy1Btn (5)) /* slow turn left */
			{
				motor[Forward_L] = slow_speed_Forward_L;
				motor[Forward_R] = slow_speed_Forward_R;
				motor[Backward_L] = slow_speed_Backward_L;
				motor[Backward_R] = slow_speed_Backward_R;
			}

			motor[Forward_L] = 0;
			motor[Forward_R] = 0;
			motor[Backward_L] = 0;
			motor[Backward_R] = 0;
		}

		if (joy1Btn (6))
	  {
	  	servo[S_Forward_L] = 128;
			servo[S_Forward_R] = 128;
			servo[S_Backward_L] = 128;
			servo[S_Backward_R] = 128;

			if (i != 2)
			{
				wait10Msec(50);
				i = 2;
			}

			while (joy1Btn (6)) /* slow turn right*/
			{
				motor[Forward_L] = slow_m_speed_Forward_L;
				motor[Forward_R] = slow_m_speed_Forward_R;
				motor[Backward_L] = slow_m_speed_Backward_L;
				motor[Backward_R] = slow_m_speed_Backward_R;
			}

			motor[Forward_L] = 0;
			motor[Forward_R] = 0;
			motor[Backward_L] = 0;
			motor[Backward_R] = 0;
		}

		if (joystick.joy1_TopHat == 2)
	  {

	  	servo[S_Forward_L] = 0;
			servo[S_Forward_R] = 255;
			servo[S_Backward_L] = 255;
			servo[S_Backward_R] = 0;

			if (i != 1)
			{
				wait10Msec(50);
				i = 1;
			}

			while (joystick.joy1_TopHat == 2) /* slow move right */
			{
				motor[Forward_L] = slow_m_speed_Forward_L;
				motor[Forward_R] = slow_speed_Forward_R;
				motor[Backward_L] = slow_speed_Backward_L;
				motor[Backward_R] = slow_m_speed_Backward_R;
			}

			motor[Forward_L] = 0;
			motor[Forward_R] = 0;
			motor[Backward_L] = 0;
			motor[Backward_R] = 0;
		}

		if (joystick.joy1_TopHat == 6)
	  {

	  	servo[S_Forward_L] = 0;
			servo[S_Forward_R] = 255;
			servo[S_Backward_L] = 255;
			servo[S_Backward_R] = 0;

			if (i != 1)
			{
				wait10Msec(50);
				i = 1;
			}

			while (joystick.joy1_TopHat == 6) /* slow move left */
			{
				motor[Forward_L] = slow_speed_Forward_L;
				motor[Forward_R] = slow_m_speed_Forward_R;
				motor[Backward_L] = slow_m_speed_Backward_L;
				motor[Backward_R] = slow_speed_Backward_R;
			}

			motor[Forward_L] = 0;
			motor[Forward_R] = 0;
			motor[Backward_L] = 0;
			motor[Backward_R] = 0;
		}

		if (joystick.joy1_TopHat == 4)
	  {
	  	servo[S_Forward_L] = 255;
			servo[S_Forward_R] = 0;
			servo[S_Backward_L] = 0;
			servo[S_Backward_R] = 255;

			if (i != 0)
			{
				wait10Msec(50);
				i = 0;
			}

	  	while (joystick.joy1_TopHat == 4) /* slow move backward */
			{
				motor[Forward_L] = slow_speed_Forward_L;
				motor[Forward_R] = slow_m_speed_Forward_R;
				motor[Backward_L] = slow_speed_Backward_L;
				motor[Backward_R] = slow_m_speed_Backward_R;
			}

			motor[Forward_L] = 0;
			motor[Forward_R] = 0;
			motor[Backward_L] = 0;
			motor[Backward_R] = 0;
		}

		if (joystick.joy1_TopHat == 0)
	  {
	  	servo[S_Forward_L] = 255;
			servo[S_Forward_R] = 0;
			servo[S_Backward_L] = 0;
			servo[S_Backward_R] = 255;

			if (i != 0)
			{
				wait10Msec(50);
				i = 0;
			}

			while (joystick.joy1_TopHat == 0) /* slow move forward */
			{
				motor[Forward_L] = slow_m_speed_Forward_L;
				motor[Forward_R] = slow_speed_Forward_R;
				motor[Backward_L] = slow_m_speed_Backward_L;
				motor[Backward_R] = slow_speed_Backward_R;
			}

			motor[Forward_L] = 0;
			motor[Forward_R] = 0;
			motor[Backward_L] = 0;
			motor[Backward_R] = 0;
		}

		if (joystick.joy1_y1 > stic_pog || joystick.joy1_y1 < m_stic_pog || joystick.joy1_x1 > stic_pog || joystick.joy1_x1 < m_stic_pog)
		{
			servo[S_Forward_L] = 128;
			servo[S_Forward_R] = 128;
			servo[S_Backward_L] = 128;
			servo[S_Backward_R] = 128;

			if (i != 2)
			{
				wait10Msec(50);
				i = 2;
			}

			while (joystick.joy1_y1 > stic_pog || joystick.joy1_y1 < m_stic_pog || joystick.joy1_x1 > stic_pog || joystick.joy1_x1 < m_stic_pog)
			{
				motor[Backward_R] = (joystick.joy1_x1 - joystick.joy1_y1) * m_small_k;
	    	motor[Forward_R] = (joystick.joy1_x1 + joystick.joy1_y1) * small_k;
	    	motor[Backward_L] = (joystick.joy1_y1 - joystick.joy1_x1) * m_small_k;
	    	motor[Forward_L] = (joystick.joy1_y1 + joystick.joy1_x1) * m_small_k;
			}

			motor[Forward_L] = 0;
			motor[Forward_R] = 0;
			motor[Backward_L] = 0;
			motor[Backward_R] = 0;
		}

		if (joystick.joy1_y2 > stic_pog || joystick.joy1_y2 < m_stic_pog || joystick.joy1_x2 > stic_pog || joystick.joy1_x2 < m_stic_pog)
		{
			servo[S_Forward_L] = 128;
			servo[S_Forward_R] = 128;
			servo[S_Backward_L] = 128;
			servo[S_Backward_R] = 128;

			if (i != 2)
			{
				wait10Msec(50);
				i = 2;
			}

			while (joystick.joy1_y2 > stic_pog || joystick.joy1_y2 < m_stic_pog || joystick.joy1_x2 > stic_pog || joystick.joy1_x2 < m_stic_pog)
			{
				motor[Backward_R] = (joystick.joy1_x2 - joystick.joy1_y2) * m_big_k;
	    	motor[Forward_R] = (joystick.joy1_x2 + joystick.joy1_y2) * big_k;
	    	motor[Backward_L] = (joystick.joy1_y2 - joystick.joy1_x2) * m_big_k;
	    	motor[Forward_L] = (joystick.joy1_y2 + joystick.joy1_x2) * m_big_k;
			}

			motor[Forward_L] = 0;
			motor[Forward_R] = 0;
			motor[Backward_L] = 0;
			motor[Backward_R] = 0;
		}

		motor[Forward_L] = 0;
		motor[Forward_R] = 0;
		motor[Backward_L] = 0;
		motor[Backward_R] = 0;
	}
}

task capture ()
{

	nMotorEncoder[motorG] = 0;

  while (true)
  {
    while (joy2Btn(2) /*&& nMotorEncoder(motorG) > 0*/)
	  {
		  Capture_Raise_1 = 100;
		  Capture_Raise_2 = -100;
	  }

	  while (joy2Btn(4) && nMotorEncoder(motorG) < 5150)
	  {
		  Capture_Raise_1 = -100;
		  Capture_Raise_2 = 100;
	  }
	 // nxtDisplayCenteredBigTextLine(3, "%i", nMotorEncoder[motorG]);

	  while (joystick.joy2_TopHat == 0)
	  {
	  	Capture_Control_Raise_1 = 100;
	  	Capture_Control_Raise_2 = 100;
	  }

		while (joystick.joy2_TopHat == 4)
		{
			Capture_Control_Raise_1 = -100;
	  	Capture_Control_Raise_2 = -100;
		}

		while (joy2Btn(10))
		{
			Robot_Raise_1 = 100;
			Robot_Raise_2 = -100;
		}

		while (joy2Btn (9))
		{
			Robot_Raise_1 = -100;
			Robot_Raise_2 = 100;
		}

	  Robot_Raise_1 = 0;
	  Robot_Raise_2 = 0;
	  Capture_Raise_1 = 0;
	  Capture_Raise_2 = 0;
	  Capture_Control_Raise_1 = 10;
	  Capture_Control_Raise_2 = 10;
	}
}

task capture2 ()
{
	bool flag = 0, flag2 = 0, flag3 = 0;

	while (true)
	{
		if (joy2Btn (8))
    {
    	flag = !flag;

      if (flag)
      	Capture_Control = 0;
 	    else
 	    	Capture_Control = 255;

    	while (joy2Btn (8))
    		getJoystickSettings(joystick);
    }

    if (joy2Btn (7))
    {
    	flag2 = !flag2;

      if (flag2)
      	servo[servo7] = 255;
 	    else
 	    	servo[servo7] = 0;

    	while (joy2Btn (7))
    		getJoystickSettings(joystick);
    }

    if (joy2Btn (5))
    {
    	flag3 = !flag3;

      if (flag3)
      {
      	servo[servo8] = 255;
	      servo[servo9] = 255;
      }
 	    else
 	    {
 	    	servo[servo8] = 0;
	      servo[servo9] = 0;
 	    }

    	while (joy2Btn (5))
    		getJoystickSettings(joystick);
    }
	}
}

task main()
{
	motor[Forward_L] = 0;
	motor[Forward_R] = 0;
	motor[Backward_L] = 0;
	motor[Backward_R] = 0;

	servo[S_Forward_L] = 255;
	servo[S_Forward_R] = 0;
	servo[S_Backward_L] = 0;
	servo[S_Backward_R] = 255;

	servo[S_Flag_Raise1] = 127;
	servo[S_Flag_Raise2] = 127;
	servo[S_Flag_Raise3] = 127;

	servo[servo8] = 0;
	servo[servo9] = 0;
	servo[servo7] = 0;
	Capture_Control = 255;

	servo[S_Autonom_Cube] = 0;

	initializeRobot();
	waitForStart();

	StartTask(capture2);
	StartTask(capture);
	StartTask(move);
	StartTask(flag_raise_and_autonom_cube);

	while (true)
		getJoystickSettings(joystick);
}
